Repository ferdousr3/school-management, pull requests merged in 2022-11, with the labels that each got.

#17 Fa/ds blog p 16
  src/Dashboard/Blogs/AddBlogModal.tsx
  src/Dashboard/Blogs/AddNewBlogs.tsx
  src/Dashboard/Blogs/AddNewBlogs3.tsx
  src/Dashboard/Blogs/AllBlogs.tsx
  src/Dashboard/Blogs/DefaultValue.tsx
  src/Dashboard/Blogs/Styles/AddNewBlogStyles.tsx
  src/Dashboard/Blogs/Styles/AllBlogStyles.tsx
  src/Routes/AppRoutes.tsx
  src/common/FromInputs/FormInputDefaultText.tsx
  src/common/FromInputs/FormInputDropdown.tsx
  src/common/FromInputs/FormInputTextarea.tsx
  src/common/FromInputs/FromInputText.tsx
  src/common/FromInputs/InputFileUpload.tsx
  src/common/FromInputs/Styles/FromInputStyles.tsx
  src/data/blog.json
  src/data/data.tsx
  src/pages/Login/Login.tsx
  src/utils/ApiLInk.tsx
  src/utils/TodayDate.tsx
  src/utils/Types.ts
  src/utils/YupBlogSchema.tsx
Labels: bug, enhancement

#18 Fa/blog page 8
  package-lock.json
  public/BlogData.json
  public/EventsData.json
  public/InstructorsData.json
  src/Hooks/useBlogDetails.tsx
  src/Routes/AppRoutes.tsx
  src/Routes/MainLyout.tsx
  src/assets/Blog/seo.png
  src/assets/Blog/we.jpg
  src/assets/hero/hero.jpg
  src/assets/hero/hero11.png
  src/assets/hero/school-library.png
  src/assets/instructors/inst1.jpg
  src/assets/instructors/inst2.jpg
  src/assets/instructors/inst3.jpg
  src/assets/instructors/inst4.jpg
  src/assets/instructors/instra.png
  src/assets/pagedetails/banner.jpg
  src/assets/pagedetails/pageDetails.jpg
  src/assets/pagedetails/pageDetails1.jpg
  src/assets/pagedetails/pageDetails2.png
  src/common/Footer/FooterLastPart.tsx
  src/common/Header/Header.tsx
  src/common/Header/Styles/HeaderStyles.tsx
  src/common/PageDetails/PageDetails.tsx
  src/components/Hero/styles/HeroStyles.tsx
  src/config/theme.config.tsx
  src/data/data.tsx
  src/index.css
  src/pages/Blogs/Blog.tsx
  src/pages/Blogs/BlogDetails.tsx
  src/pages/Blogs/Blogs.tsx
  src/pages/Blogs/Style/BlogStyles.tsx
  src/pages/Courses/Course.tsx
  src/pages/Courses/CourseCard.tsx
  src/pages/Courses/Courses.tsx
  src/pages/Events/Event.tsx
  src/pages/Events/Events.tsx
  src/pages/Events/EventsCard.tsx
  src/pages/Home/Home.tsx
  src/pages/Instructors/InstructorCards.tsx
  src/pages/Instructors/Instructors.tsx
  src/pages/Instructors/Styles/InstaStyle.tsx
  src/pages/test.tsx
  src/styles/index.css
Labels: enhancement

#23 Fa/user blog da 20
  package-lock.json
  package.json
  src/App.tsx
  src/Dashboard/Blogs/AllBlogs.tsx
  src/Dashboard/Blogs/AllBlogsTableTop.tsx
  src/Dashboard/Blogs/BlogActionButton.tsx
  src/Dashboard/Blogs/BlogColumns/BlogColumns.tsx
  src/Dashboard/Blogs/Modal/BlogEditModal.tsx
  src/Dashboard/Blogs/Styles/AllBlogStyles.tsx
  src/Dashboard/Blogs/Title.tsx
  src/Dashboard/Layout/Dashboard.tsx
  src/Dashboard/Layout/DashboardHeader.tsx
  src/Dashboard/Layout/DashboardLayout.tsx
  src/Dashboard/Layout/DrawerItems.tsx
  src/Dashboard/Layout/DrawerProfileCard.tsx
  src/Dashboard/Layout/Styles/DashboardLayoutStyle.tsx
  src/Dashboard/Layout/Styles/DashboardStyles.tsx
  src/Routes/AppRoutes.tsx
  src/common/DataTable/DataTable.tsx
  src/common/DataTable/Styles/DataTableStyles.tsx
  src/config/theme.config.tsx
  src/data/data.tsx
  src/styles/index.css
  src/theme.d.ts
  src/utils/Types.ts
Labels: enhancement

#24 #20 fix bugs
  src/Dashboard/Blogs/AllBlogs.tsx
  src/Dashboard/Blogs/BlogActionButton.tsx
  src/Dashboard/Blogs/BlogColumns/BlogColumns.tsx
  src/auth/PasswordReset.tsx
  src/common/DataTable/Styles/DataTableStyles.tsx
Labels: bug

#25 #20 fix bugs
  src/Dashboard/Blogs/AllBlogs.tsx
Labels: bug
